import json
from pathlib import Path

import numpy as np

from kim_qa.metrics import overlay_metrics_table, overlay_residuals
from kim_qa.server.config import ServerConfig
from kim_qa.server.discovery import discover_sessions
from kim_qa.server.state import (
    STATE_FILENAME, load_state, regenerate_summary, update_entry,
)
from tests.fixtures import (
    make_baseline_pair, make_motion_session, write_centroid_file,
    write_ga_file, write_kim_file,
)

RED = '<span style="color:#c0392b">'

GOLDEN = Path(__file__).parent / "golden" / "overlay_metrics.json"


def sample_data():
    hex_t = np.arange(0.0, 30.0, 0.02)
    hex_si = 2.0 * np.sin(2 * np.pi * 0.2 * hex_t)
    hex_lr = 0.3 * np.cos(2 * np.pi * 0.1 * hex_t)
    hex_ap = 0.5 * np.sin(2 * np.pi * 0.15 * hex_t)
    kim_t = np.linspace(0.0, 20.0, 60)
    off = 4.0
    kim_lr = np.interp(kim_t + off, hex_t, hex_lr) + 0.1
    kim_si = np.interp(kim_t + off, hex_t, hex_si) - 0.2
    kim_ap = np.interp(kim_t + off, hex_t, hex_ap) + 0.05
    return kim_t, kim_lr, kim_si, kim_ap, hex_t, hex_lr, hex_si, hex_ap, off


def test_overlay_metrics_known_bias():
    kt, klr, ksi, kap, ht, hlr, hsi, hap, off = sample_data()
    res = overlay_residuals(kt, klr, ksi, kap, ht, hlr, hsi, hap, off, [])
    rows = {r["name"]: r for r in overlay_metrics_table(res)}
    assert np.isclose(rows["LR"]["mean"], 0.1, atol=1e-6)
    assert np.isclose(rows["SI"]["mean"], -0.2, atol=1e-6)
    assert rows["LR"]["std"] < 1e-6            # constant bias, ddof=1 std ~ 0
    assert rows["3D"]["mean"] > 0
    assert res.n == 60


def test_ranges_restrict_samples():
    kt, klr, ksi, kap, ht, hlr, hsi, hap, off = sample_data()
    res = overlay_residuals(kt, klr, ksi, kap, ht, hlr, hsi, hap, off,
                            [[4.0, 9.0]])
    assert 0 < res.n < 60
    assert np.isclose(res.total_dt, 5.0)


def test_export_golden():
    """Write the golden file consumed by webapp/src/metrics-golden.test.ts."""
    kt, klr, ksi, kap, ht, hlr, hsi, hap, off = sample_data()
    res = overlay_residuals(kt, klr, ksi, kap, ht, hlr, hsi, hap, off, [])
    rows = overlay_metrics_table(res)
    GOLDEN.parent.mkdir(exist_ok=True)
    GOLDEN.write_text(json.dumps({
        "kim": {"t": kt.tolist(), "lr": klr.tolist(), "si": ksi.tolist(),
                "ap": kap.tolist()},
        "hex": {"t": ht.tolist(), "lr": hlr.tolist(), "si": hsi.tolist(),
                "ap": hap.tolist()},
        "offset": off,
        "expected_rows": rows,
    }))
    assert GOLDEN.exists()


def test_state_roundtrip_preserves_unknown_keys(tmp_path):
    (tmp_path / STATE_FILENAME).write_text(json.dumps(
        {"old-session": {"offset": 1.0, "custom_key": "kept"}}))
    update_entry(tmp_path, "new-session",
                 {"offset": 2.5, "ranges": [[1, 2]], "y_range": 10})
    state = load_state(tmp_path)
    assert state["old-session"]["custom_key"] == "kept"
    assert state["new-session"]["offset"] == 2.5


def test_regenerate_summary(tmp_path):
    traces = tmp_path / "Motion traces"
    make_motion_session(tmp_path, traces)
    cfg = ServerConfig(root=tmp_path)
    sessions = discover_sessions(cfg)
    update_entry(tmp_path, "lung-typical,Test_1518",
                 {"offset": 3.0, "ranges": []})
    out = regenerate_summary(tmp_path, sessions, "Elekta")
    text = out.read_text(encoding="utf-8")
    assert "lung-typical,Test_1518" in text
    assert "| Axis | Mean (mm) |" in text
    assert "Generated by KIM-QA-Server" in text


def test_summary_includes_offline_overlays(tmp_path):
    """A nested kim-log* folder gets its own overview row and detail metrics
    table, computed with its saved per-offline offset (not the primary's)."""
    traces = tmp_path / "Motion traces"
    sess = make_motion_session(tmp_path, traces)
    # Offline replay on its own timebase: sampled from the hex at +5 s, with a
    # constant +0.3 mm LR bias so its metrics differ visibly from the primary.
    off_dir = sess / "kim-log-pdf480"
    off_dir.mkdir()
    t = np.arange(100) * 0.25
    u = t + 5.0
    si = 2.0 * np.sin(2 * np.pi * 0.2 * u) + 0.1 * u
    lr = 0.2 * np.sin(2 * np.pi * 0.1 * u) + 0.3
    ap = 0.5 * np.sin(2 * np.pi * 0.15 * u)
    write_ga_file(off_dir / "MarkerLocationsGA_CouchShift_0.txt", t, ap, lr, si,
                  np.linspace(180.0, 100.0, len(t)))
    cfg = ServerConfig(root=tmp_path)
    sessions = discover_sessions(cfg)
    update_entry(tmp_path, "lung-typical,Test_1518",
                 {"offset": 3.0, "ranges": [],
                  "offline_offsets": {"kim-log-pdf480": 5.0}})
    text = regenerate_summary(tmp_path, sessions, "Elekta").read_text(
        encoding="utf-8")

    # Overview: one extra row for the offline run, at its own offset.
    row = next(ln for ln in text.splitlines()
               if ln.startswith("| lung-typical,Test_1518 / pdf480 |"))
    assert "| offline | +5.00 |" in row
    # Detail: a subsection with its own metrics table showing the LR bias.
    assert "### Offline: pdf480" in text
    idx = text.index("### Offline: pdf480")
    lr_line = next(ln for ln in text[idx:].splitlines()
                   if ln.startswith("| LR |"))
    assert "+0.300" in lr_line


def test_summary_offline_overlay_falls_back_to_primary_offset(tmp_path):
    """An offline overlay with no saved offset is reported at the primary
    run's offset."""
    traces = tmp_path / "Motion traces"
    sess = make_motion_session(tmp_path, traces)
    off_dir = sess / "kim-log-pdf480"
    off_dir.mkdir()
    t = np.arange(100) * 0.25
    u = t + 3.0
    si = 2.0 * np.sin(2 * np.pi * 0.2 * u) + 0.1 * u
    lr = 0.2 * np.sin(2 * np.pi * 0.1 * u)
    ap = 0.5 * np.sin(2 * np.pi * 0.15 * u)
    write_ga_file(off_dir / "MarkerLocationsGA_CouchShift_0.txt", t, ap, lr, si,
                  np.linspace(180.0, 100.0, len(t)))
    cfg = ServerConfig(root=tmp_path)
    sessions = discover_sessions(cfg)
    update_entry(tmp_path, "lung-typical,Test_1518",
                 {"offset": 3.0, "ranges": []})
    text = regenerate_summary(tmp_path, sessions, "Elekta").read_text(
        encoding="utf-8")
    row = next(ln for ln in text.splitlines()
               if ln.startswith("| lung-typical,Test_1518 / pdf480 |"))
    assert "| offline | +3.00 |" in row


def test_summary_baseline_session_uses_hex_t_and_labels(tmp_path):
    """A baseline-GT session's summary shows the baseline label, the no-centroid
    note, and metrics computed against the baseline's irregular timebase (the
    fixture pair coincides at offset 0.5 -> near-zero residuals)."""
    make_baseline_pair(tmp_path)
    cfg = ServerConfig(root=tmp_path)
    overrides = {"2026-08-07-Pat03": "baseline:2026_06_17-pat03"}
    sessions = discover_sessions(cfg, overrides)
    update_entry(tmp_path, "2026-08-07-Pat03",
                 {"offset": 0.5, "ranges": [],
                  "hex_override": "baseline:2026_06_17-pat03",
                  "gantry_remap": True})
    text = regenerate_summary(tmp_path, sessions, "Elekta").read_text(
        encoding="utf-8")
    assert "baseline 2026_06_17-pat03 (gantry-remapped)" in text
    assert "Centroid: none (offset 0)" in text or \
        "**Centroid:** none (offset 0)" in text
    lr_line = next(ln for ln in text.splitlines() if ln.startswith("| LR |"))
    # residuals near zero -> no red span on the LR row
    assert RED not in lr_line
    assert "| LR | +0.0" in lr_line or "| LR | -0.0" in lr_line


def test_summary_red_spans_on_failing_axes(tmp_path):
    """A large constant AP bias (flat-zero session -> residuals == KIM values)
    must wrap the failing AP mean in the red span, while a passing LR value and
    the whole 3D row stay unwrapped. Numbers themselves are unchanged."""
    name = "Static,BigBias_1600"
    sess = tmp_path / name
    sess.mkdir(parents=True, exist_ok=True)
    t = np.arange(0.0, 20.0, 1.0)
    z = np.zeros(20)
    # write_kim_file(path, t, ap, lr, si): AP=+5 fails |mean|>1, LR=+0.1 passes.
    write_kim_file(sess / "MarkerLocations_CouchShift_0.txt",
                   t, z + 5.0, z + 0.1, z)
    write_centroid_file(sess / "Phantom_Centroid.txt")
    cfg = ServerConfig(root=tmp_path)
    sessions = discover_sessions(cfg)
    update_entry(tmp_path, name, {"offset": 0.0, "ranges": []})
    text = regenerate_summary(tmp_path, sessions, "Elekta").read_text(
        encoding="utf-8")

    # Detail table: failing AP mean wrapped; passing LR mean plain.
    assert f'| AP | {RED}+5.000</span> |' in text
    assert '| LR | +0.100 |' in text
    # 3D row is never colored, even though its magnitude (~5 mm) "fails".
    line_3d = next(ln for ln in text.splitlines() if ln.startswith('| 3D |'))
    assert RED not in line_3d
    # Overview table: failing AP mean wrapped, kept next to its ± std.
    assert f'{RED}+5.00</span>±0.00' in text
